### ISSUE TITLE
Custom RGB Devices

### ISSUE THREAD

**Issue by MihaiSvet** [MartB/RETC#10]
Hi @MartB, I want to create a customized lighting system in my room to transfer effects from Overwatch using RETC. I have no Corsair devices so based on the Corsair SDK located in the project I created my own, that, for the moment, should only log the ledId and its color. I have tried both installation methods manual and creating the installer but can't see anything in the logs at all. Could it be because I have Razer Chroma already installed in the system?

**Comment by MartB** [comment]
Hey, can you publish your changes on your Github repository?

Keep in mind that the code only supports 1 output sdk for the time being(you can change that by adapting the code). So if you have a razer keyboard connected and you are trying to use the keyboard effects in your custom sdk it wont work with my version of the code.

Kind regards
MartB

Am 03.07.2017 21:57 schrieb MihaiSvet <notifications@github.com>:

Hi @MartB<https://github.com/martb>, I want to create a customized lighting system in my room to transfer effects from Overwatch using RETC. I have no Corsair devices so based on the Corsair SDK located in the project I created my own, that, for the moment, should only log the ledId and its color. I have tried both installation methods manual and creating the installer but can't see anything in the logs at all. Could it be because I have Razer Chroma already installed in the system?

**Comment by MihaiSvet** [comment]
Actually, now I've done everything once again and I am able to see the logs.
Will try to debug it by myself and maybe create support for multiple SDKs for the same device.

I think you can close this now and in the case of any issues, I'll get in touch.

Will push the changes when everything will be ready )

**Comment by MartB** [comment]
Alrighty
