### ISSUE TITLE
Corsair Effects Engine take the top over RETC

### ISSUE THREAD

**Issue by LightBeamOvHe** [MartB/RETC#11]
Hello
I just wanted to share a little problem that I had with the soft
I sometimes use CEE to have more effects with the keyboard, but when the soft is launched, CEE take the top over RETC and I don't have the effects in Overwatch
Of course it works properly when it's not launched
Can it be fixed ?
Thank you !

**Comment by MartB** [comment]
Uhm seems like CEE is using the exclusive mode just like my app does.
I need to add a config file in the future which would allow setting it to shared mode.
But then again im not sure if this plays nicely with CEE at all.

**Comment by LightBeamOvHe** [comment]
I made a new test, seems like the colors of RETC works properly now but the spectrograph effect still working over it (and if it want to shut down some keys it will, like the lighting effect and windows lock key, maybe because the spectrograph effect use them but not RETC)
In hope that it will be useful for you

**Comment by MartB** [comment]
My library takes the full lighting effects from the game and applies them to the respective available leds on your pc (like the razer guys intended).
It will always overwrite any key even if its "unused" (because theres no way to tell what unused means (e.g R:0 G:0 B:0 is off and not unused).

I see no way i can improve compatibility with other apps.
