### ISSUE TITLE
No signal from FL Studio Razer Chroma plugin

### ISSUE THREAD

**Issue by davidarellano** [MartB/RETC#12]
Hello,

I managed to install your wrapper on my machine, but it doesn't sync with the Razer plugin for FL Studio.
I placed the wrapper in the plugin folder (the plugin is also a .dll file). When loading the plugin inside FL Studio the wrapper seems to load and connect fine.

I can see in the log (or the terminal window) that the wrappers init fine, but nothing happens after that. I also set the exclusive mode to true and the keyboard lights became black, so it seems to be working but maybe the Razer Chroma plugin for FL Studio is not sending the data as expected. I set the effect to a plain color just in case the effect was not compatible, but no success either.

I think the FL Studio plugin is supposed to detect and highlight the connected devices, so you can select them in the UI and config the effect. Maybe this is the problem: no devices detected. I have no Razer devices so I can't test this in any way.

If anyone could take a look at it would be great. Any extra info I could provide please ask.

Thanks for your time, and congrats for your great work.

The specs where I tested this are:
Windows 10 x64
Keyboard Corsair K95 Platinum v1.07.123
Mousemat Corsair MM800 RGB Polaris v1.02.50
CUE 2.15.83
FL Studio 12.4.2

Some documentantion about the plugin:

From Image-line: https://www.image-line.com/support/FLHelp/html/plugins/Razer%20Chroma.htm
Razer Music: http://support.image-line.com/redirect/FLStudio_RazerMusic

![image](https://user-images.githubusercontent.com/4090193/28695137-bc5bcd7c-732d-11e7-8876-de1a489380d6.png)

**Comment by MartB** [comment]
Hey there,
that might actually be due to what you are describing. (The plugin might query the available devices.)
https://github.com/MartB/RETC/blob/master/shim-dll/shim.cpp#L196 does not return proper data at the moment but i could make that work like the official api does i think.

I will implement that and pack a wrapper for you to try.

**Comment by MartB** [comment]
Fixed with 3b4eae61da71967eea38c9e8f6c1703b9f72c0b0 and released as v3.2.1

Waiting for confirmation on whether or not this resolved the "issue".
Edit (Downloaded FL Studio demo and set up the plugin):
![image](https://user-images.githubusercontent.com/4820905/28696624-ee0998be-7336-11e7-83fc-93ca666393c6.png)
Seems to work fine!

Kind regards
MartB

**Comment by MartB** [comment]
This also helped find an issue with the keyboard mapping. (Thanks to the piano lights)
I fixed it with 5a192fe12175645b906c8bdb1a8d3b703444bbe8

**Comment by davidarellano** [comment]
Wow, that was fast! Thanks for your implication.

Works great on my side too. Tested with keyboard and mousemat.

Great project you have here, keep it up!

Best,
David.
