### ISSUE TITLE
Malware Issue

### ISSUE THREAD

**Issue by mcwildcard** [MartB/RETC#15]
Great fan of the program, really love using it for overwatch but recently my antivirus has been flagging the program as a trojan, more specifically the "nssm.exe" which is being read as a "trojan.win32.agentb.iwfj"

**Comment by MartB** [comment]
What AV are you using ?

Mind reporting is as suspected false positive and let them check it out ?
https://www.virustotal.com/#/file/bb006c3b8182fe230adf92744919724d241c7ebaed64192bcb3f934b0f1f6d1c/detection

3.2.3 had some AV false positives 3.2.4 is a bit better in this regard but many AVs dont like NSSM.exe because its usually bundled with trojans (sadly because its such a great software).

I might actually need to create a custom service implementation just to get rid of the constant alerts.
#16

**Comment by mcwildcard** [comment]
I'm using kaspersky antivirus, after detecting it it i'm having trouble re downloading the application because of the exe. going to try and find another way of getting it onto my computer as an exemption  thank you for a quick response though,

**Comment by MartB** [comment]
Im using kaspersky too and i will get it resolved with them for the time being.

**Comment by MartB** [comment]
```
Hello,

Sorry, it was a false detection. It will be fixed.
Thank you for your help.

Sincerely yours,
<snip>
```
Im tired of doing this for each release so stay tuned for the new version without nssm.

**Comment by MartB** [comment]
Please check the newest version 3.2.5 too!
It doesnt contain NSSM and should not get blocked by kaspersky.

**Comment by mcwildcard** [comment]
worked great, Thanks a ton

**Comment by MartB** [comment]
Thanks for your feedback.
#closed
